baseurl = "https://blog.quanteda.org/"
languageCode = "en-gb"
title = "Quanteda Initiative Blog"
theme = "hugo-type-theme"
# Enable comments by entering your Disqus shortname
disqusShortname = "quantedablog"
# Add your tracking code to enable Google Analytics
googleAnalytics = ""
# Posts per page
paginate = 10
# Comment the themesDir option if you use this theme in production
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "https://quanteda.org"
[[menu.main]]
    name = "News"
    url = "https://quanteda.org/category/news/"
[[menu.main]]
    name = "About Us"
    url = "https://quanteda.org/about-us/"
[[menu.main]]
    name = "Projects"
    url = "https://quanteda.org/projects/"
[[menu.main]]
    name = "Blog"
    url = "https://blog.quanteda.io"
[[menu.main]]
    name = "Services"
    url = "https://quanteda.org/services-2/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/quanteda/blog.quanteda.org"

[params]
	author = "Quanteda Initiative"
    title = "Quanteda Initiative Blog"
	description = "Quanteda Initiative Blog"
	# The keywords will be added as a meta tag. Delimit them with a comma.
	keywords = ""
	# Either show custom avatar on the top
	# left by adding the filename in below
	avatar = "img/logo.svg"
	# or use Gravatar by adding your email address to generate a unique avatar
	#gravatar = "your@email.com"

	# headerText = "<h1>For all the text analysts</h1> Quanteda Initiative is a non-profit organization to achieve <a href='/about'>our missions</a>"
	# To add a header background to the main site, save your image under static/img/.
	# If now image path is provided, a orange background will be shown instead.
	headerImage = ""
	copyright = "Released under the MIT license<br>Powered by [Hugo](//gohugo.io/) with the [Type Theme](//github.com/digitalcraftsman/hugo-type-theme)"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"


	[params.social]
		# Insert your account name and the icon will be shown in the right menu
		rss = true
		homepage = true
		email = "admin@quanteda.org"
		behance = ""
		bitbucket  =""
		dribbble = ""
		facebook = ""
		flickr = ""
		github = "quanteda/blog.quanteda.org"
		googleplus = ""
		instagram = ""
		linkedin = ""
		pinterest = ""
		reddit = ""
		soundcloud = ""
		stackexchange = ""
		steam = ""
		tumblr = ""
		twitter = ""
		wordpress = ""
		youtube = ""
		gitlab = ""
		trello = ""

